imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
web_profiler:
    toolbar: true
    intercept_redirects: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#FOSUser
fos_user:
    db_driver:     orm                       # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                      # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    Tfe\UserBundle\Entity\Users # La classe de l'entité User que nous utilisons
    registration:
        form:
           type: Tfe\UserBundle\Form\Type\RegistrationFormType

        confirmation:
            enabled: false
            from_email:
                address: maxence.begon147@gmail.com
                sender_name: E-mail Confirmation Plateforme Sociale
    profile:
        form:
            type: Tfe\UserBundle\Form\Type\ProfileFormType
    resetting:
        email:
           from_email:
               address: maxence.begon147@gmail.com
               sender_name: Réinitialisation mdp Plateforme Sociale
#Oauth
hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)

    connect:

    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_names: [secured_area]
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
            google: google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           '1597541063890879'
            client_secret:       'a220401dc4a770f78b9f55d002303ef7'
            scope:               "email "
            options:
                display: popup #dialog is optimized for popup window
                auth_type: rerequest # Re-asking for Declined Permissions
        google:
            type:                google
            client_id:           '812905169796-jlmohop2u01ho858h43v7pc0augjqorn.apps.googleusercontent.com'
            client_secret:       'H7B_QYJtwDb_nnbWEbPCiCA0'
            scope:               "email profile"

#fos comment
#fos_comment:
 #   db_driver: orm
  #  class:
   #     model:
    #        comment: Tfe\ForumBundle\Entity\Comment
     #       thread: Tfe\ForumBundle\Entity\Thread

#Assetic
assetic:
    debug: '%kernel.debug%'
    use_controller: '%kernel.debug%'
    #bundles: [ "FOSCommentBundle" ]

#FOS REST
#->*Paramètre à revoir car si j'enlève le hrml ds les rules je n'ai que du json et mon site ne s'affiche plus
fos_rest:
    routing_loader:
        include_format: false     #désactive l'ajout automatique de format
    view:
        #default_engine: twig
        view_response_listener:   #active le listener
            enabled: true
            force: true
        formats:
            json: true
            xml: true
            html: true
    format_listener:
        rules:
            - {path: '^/', priorities: [ 'html','json'], fallback_format:  'json', prefer_extension: false} #config pour que toutes les URL renvoient du JSON
           # - {path: 'http://tfe.plateformesociale.be:8080/tf2/plateforme_sociale/web/app_dev.php/rest/places/', priorities: ['json', 'xml'], fallback_format: 'json',  prefer_extension: false}
    # configuration à rajouter pour désactiver le body listener
    body_listener:
        enabled: true

#Api Doc
nelmio_api_doc: ~
framework:
    templating:
        engines: ['twig']



#pagination
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

#vich uploader
vich_uploader:
    db_driver: orm
    twig: true
    storage: file_system
    mappings:
        user_image:
            uri_prefix:         /images/avatars  # todo pour que l'affichage d'image fct avec wampserver il faut changer le lien ici.
            upload_destination: %kernel.root_dir%/../web/images/avatars
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

#bbcode
fm_bbcode:
      filter_sets:
        my_default_filter:
          strict: false # if you want to parse attr values without quotes
          locale: ru
          xhtml: true
          filters: [ default, quote ]
          whitelist: [ b,i,u, quote ]
        my_forum_filter:
           locale: ru
           xhtml: true
           filters: [ default, quote ]
           whitelist: [ b, quote ]
        my_comment_filter:
           locale: ru
           xhtml: true
           filters: [ default, block, code, email, image, list, quote, text, url, video ]
      config:
        templates:
          - path: '@TfePlatformSocialeBundle/Resources/views/Publications/publications.html.twig'

