tfe_core:
    resource: "@TfeCoreBundle/Resources/config/routing.yml"
    prefix:   /

tfe_platforme_sociale:
    resource: "@TfePlatformSocialeBundle/Resources/config/routing.yml"
    prefix:   /plateforme-sociale