security:
  encoders:
    Tfe\UserBundle\Entity\Users: sha512

  role_hierarchy:
    # Un admin hérite des droits d'auteur et de modérateur
    ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
    # On garde ce rôle superadmin, il nous resservira par la suite
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
      main:
            id: fos_user.user_provider.username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    secured_area:
      pattern:      ^/
      anonymous:    true
      provider:     main
      form_login:
          provider: main
          login_path: /login
          check_path: /login_check

          # login success redirecting options (read further below)
          always_use_default_target_path: true
          default_target_path:   /plateforme-sociale



      logout: true
      anonymous: true


      oauth:
          resource_owners:
              facebook: "/login/check-facebook"
              google:   "/login/check-google"
          login_path:        /login
          failure_path:      /login

          oauth_user_provider:
              service: my_user_provider

    login:
        pattern:  ^/login/
        security: false

        remember_me:
           secret:    %secret% #%secret% est un paramètre de parameter
           path: /
           domain: ~

  access_control:
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/, role: ROLE_ADMIN }
      - { path: ^/plateforme-sociale/, role: ROLE_ADMIN }