tfe_platform_sociale_homepage:
    path:     /
    defaults: { _controller: TfePlatformSocialeBundle:Default:index }


tfe_rest_publication:
    type: rest
    resource: "@TfePlatformSocialeBundle/Controller/PublicationApiController.php"

tfe_platform_sociale_publication:
    path:     /publications
    defaults: { _controller: TfePlatformSocialeBundle:Publication:Publications }

tfe_platform_sociale_publication_keywords:
    path:     /publications/keywords
    defaults: { _controller: TfePlatformSocialeBundle:Publication:PublicationsKeywords }

tfe_api_:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc