tfe_platform_sociale_homepage:
    path:     /
    defaults: { _controller: TfePlatformSocialeBundle:Default:index }



tfe_rest_publication:
    type: rest
    resource: "@TfePlatformSocialeBundle/Controller/PublicationApiController.php"

tfe_platform_sociale_publication:
    path:     /publications
    defaults: { _controller: TfePlatformSocialeBundle:Publication:Publications }

tfe_platform_sociale_update_publication:
    path:     /publication/update/{id}
    defaults: { _controller: TfePlatformSocialeBundle:Publication:updatePublication }

tfe_platform_sociale_delete_publication:
    path:     /publication/delete
    defaults: { _controller: TfePlatformSocialeBundle:Publication:deletePublication }

tfe_platform_sociale_publication_keywords:
    path:     /publications/keywords/{kw}
    defaults: { _controller: TfePlatformSocialeBundle:Publication:PublicationsKeywords }


tfe_platform_sociale_publication_addComment:
    path:     /publications/comment
    defaults: { _controller: TfePlatformSocialeBundle:Publication:PublicationAddComment }

tfe_platform_sociale_publication_updateComment:
    path:     /publications/update/comment/{id}
    defaults: { _controller: TfePlatformSocialeBundle:Publication:PublicationUpdateComment }

tfe_platform_sociale_publication_deleteComment:
    path:     /publications/delete/comment/{id}
    defaults: { _controller: TfePlatformSocialeBundle:Publication:PublicationDeleteComment }

tfe_platform_sociale_user_add_point:
    path:     /point/{id}
    defaults: { _controller: TfePlatformSocialeBundle:Publication:Point }

tfe_api_:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc