
services:
    tfe.form.registration:
        class: Tfe\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: tfe_user_registration }

    tfe.form.profile.edit:
        class: Tfe\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.edit.type, alias: tfe_user_profile_edit }


    my_user_provider:
        class: Tfe\UserBundle\Security\Core\User\FOSUBUserProvider
        arguments: ['@fos_user.user_manager', { facebook: facebook_id, google: google_id }]
