<?php

namespace Tfe\PlatformSocialeBundle\Repository;

/**
 * CommentPublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentPublicationRepository extends \Doctrine\ORM\EntityRepository
{
}
