<?php

namespace Tfe\PlatformSocialeBundle\Repository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.nameGenre', 'ASC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
