<?php

namespace Tfe\UserBundle\Repository;

/**
 * AbonnementUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnementUserRepository extends \Doctrine\ORM\EntityRepository
{
}
