<?php

namespace Tfe\UserBundle\Repository;

/**
 * StatutUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutUserRepository extends \Doctrine\ORM\EntityRepository
{
}
