<?php

namespace Tfe\UserBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class UsersRepository extends \Doctrine\ORM\EntityRepository
{

    public function AscAll()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.username', 'ASC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }


    public function DescAll()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.username', 'DESC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
