<?php

namespace Tfe\UserBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class UsersRepository extends \Doctrine\ORM\EntityRepository
{

    public function FindUsersAscAll()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.username', 'ASC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }


    public function FindUsersDescAll()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.username', 'DESC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function FindUsersAsc($name)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where("a.username like '%".$name."%'");
        $qb->orderBy('a.username', 'ASC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }


    public function FindUsersDesc($name)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where("a.username like '%".$name."%'");
        $qb->orderBy('a.username', 'DESC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function ResearchUser($name)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where("a.username like '%".$name."%'");
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
