<?php

namespace Tfe\ForumBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll()
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a.title,a.id, a.group');

        $qb->orderBy('a.title', 'ASC');

        return $qb
            ->getQuery()
            ->getResult();


    }
    public function myFindAllByGroup($groupId)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a.title,a.id');
        $qb->where('a.groupId = :gpId')
            ->setParameter('gpId', $groupId);
        $qb->orderBy('a.title', 'ASC');

        return $qb
            ->getQuery()
            ->getResult();


    }
}