<?php

namespace Tfe\ForumBundle\Repository;

/**
 * ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAllThread()
    {
        $qb = $this->createQueryBuilder('a');

        //$qb->select('a.title,a.id');

        $qb->orderBy('a.title', 'ASC');

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}

