<?php

namespace Tfe\ForumBundle\Repository;

/**
 * ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAllThread($cat)
    {
        $qb = $this->createQueryBuilder('a');

        //$qb->select('a.title,a.id');
        $qb->where('a.category = :cat')
            ->setParameter('cat', $cat)
        ->orderBy('a.title', 'ASC');

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function deleteThread($idThread)
    {

    }

    /*
     * public function myFindAllByGroup($groupId)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a.title,a.id');
        $qb->where('a.groupe = :gpId')
            ->setParameter('gpId', $groupId);
        $qb->orderBy('a.title', 'ASC');

        return $qb
            ->getQuery()
            ->getResult();


    }
     */
}

