tfe_forum_homepage:
    path:     /
    defaults: { _controller: TfeForumBundle:Default:index }


tfe_add_category:
    path:     /category_add
    defaults: { _controller: TfeForumBundle:Default:addCategory }

tfe_forum_category:
    path:     /category/{id}
    defaults: { _controller: TfeForumBundle:Category:index }

tfe_add_thread:
    path:     /thread_add
    defaults: { _controller: TfeForumBundle:Category:addThread }

tfe_forum_thread:
    path:     /thread/{id}
    defaults: { _controller: TfeForumBundle:Thread:index }

tfe_delete_comment:
    path: /comment/delete/{idComment}/{idThread}
    defaults: { _controller: TfeForumBundle:Thread:deleteComment }

tfe_delete_thread:
    path: /thread/delete/{idThread}
    defaults: { _controller: TfeForumBundle:Thread:deleteThread }

tfe_delete_category:
    path: /category/delete/{categoryId}
    defaults: { _controller: TfeForumBundle:Category:deleteCategory }

tfe_delete_group:
    path: /groupe/delete
    defaults: { _controller: TfeForumBundle:Default:deleteGroup }

tfe_update_comment:
    path: /comment/update/{idComment}
    defaults: { _controller: TfeForumBundle:Thread:updateComment }

tfe_forum_add_point:
    path: /point/{id}
    defaults: { _controller: TfeForumBundle:Thread:addPointUser }