tfe_forum_homepage:
    path:     /
    defaults: { _controller: TfeForumBundle:Default:index }


tfe_add_category:
    path:     /category_add
    defaults: { _controller: TfeForumBundle:Default:addCategory }

tfe_forum_category:
    path:     /category/{id}
    defaults: { _controller: TfeForumBundle:Category:index }

tfe_add_thread:
    path:     /thread_add
    defaults: { _controller: TfeForumBundle:Category:addThread }

tfe_forum_thread:
    path:     /thread/{id}
    defaults: { _controller: TfeForumBundle:Thread:index }

tfe_delete_comment:
    path: /comment/delete/{idComment}/{idThread}
    defaults: { _controller: TfeForumBundle:Thread:deleteComment }